### ISSUE TITLE
Crash Loop If Non-Existent Item In Manual Dock

### ISSUE THREAD

**Issue by REALtony4twenty** [FiniteSingularity/obs-quick-access-utility#18]
Crash Loop If Non-Existent Item In Manual Dock

**Steps to reproduce**
1. Create a manual dock
2. Create a scene
3. Create an item in the new scene
4. Add this new item into the manual dock
5. Delete the scene
6. Close OBS without removing item from list
7. Trying to reopen OBS without uninstalling plugin first

**Expected behavior**
Deleting scenes/scene items updates list

**Environment**
 - Windows 11
 - OBS Version: 30.1.2
 - Dock Type: Manual

**GPU**
 - GPU make/model: NVIDIA GeForce RTX 4080 SUPER (MSI)
 - GPU VRAM: 16GB

**Additional context**
Changing their settings, transform, and filters do not seem to cause a crash. With no manual dock, but using a dynamic and search dock with a source loaded into both to edit from a scene you then delete, closing OBS seems to have an issue but it does not crash upon re-opening (potential loss of changes due to save issue on close I imagine)

**Comment by REALtony4twenty** [comment]
Fixed in new push

**Comment by FiniteSingularity** [comment]
Just to track.  Fixed by #17
