### ISSUE TITLE
[Feature] Combine Source Search Dock  and Dynamic Dock

### ISSUE THREAD

**Issue by REALtony4twenty** [FiniteSingularity/obs-quick-access-utility#22]
**Request**
Add the Source Search dock functionality to Dynamic Dock, allowing users to use it more similarly to the Manual Dock where you can access scene items from scenes they are not in. Would actually prefer this method over Manual dock as I will me adding/removing items from the dock more than keeping items saved in the list.

**Describe the solution you'd like**
Add the same search bar from the "Source Search" dock type into the dynamic type and have the found/matching items either pop up in the main list but above the current scenes list or in a submenu.

**Additional context**
If Im in my main scene and I notice something happen to a source and I want to fix it, I can use this method to just searching for it, making a fix and then moving on without the need to add it to the list, make the fix, then remove it from the list since i more than likely wont need to edit it again later on.

**Comment by FiniteSingularity** [comment]
Closed with #44

**Comment by REALtony4twenty** [comment]
So there was a slight misunderstanding. The work done is still great :D 
However, I was more so requesting the search from Source Search and Dynamic to share properties
![image](https://github.com/user-attachments/assets/2cd6cf2e-5940-4e0d-b8bd-d673687cf95a)
This way, I can use the dynamic dock, BUT still find sources that are in other scenes. As shown above with the source search dock, even though I am in a scene with only a browser source, I can still search for the glow source that is in scene 2. 
I would like to be able to do this as well, but with the dynamic dock. Allowing it to have all current scenes sources in a list BUT also find other sources to quickly edit them

**Comment by FiniteSingularity** [comment]
From a UI point of view, I am not a big fan of that kind of mixed functionality (I think it would get quite confusing for most users).  That said,  I am currently cooking something up, that I think will definitely scratch this itch.  Stay tuned.
