### ISSUE TITLE
[Feature] Change Source/Scene Names

### ISSUE THREAD

**Issue by REALtony4twenty** [FiniteSingularity/obs-quick-access-utility#29]
**Is your feature request related to a problem? Please describe.**
Ability to change the name of sources/scenes

**Describe the solution you'd like**
In #27 I mention a adding a submenu to the originally "properties" icon. I would recommend adding this option here where when selected, it opens a text box like the search box and whatever you type in becomes the new name of the source.

**Comment by FiniteSingularity** [comment]
This (And some of your other ideas) will likely be implemented in a right-click contextual menu that I'm working on adding.
