### ISSUE TITLE
[Feature] Media Controls

### ISSUE THREAD

**Issue by REALtony4twenty** [FiniteSingularity/obs-quick-access-utility#30]
**Request**
Big ask but for those who watch videos and commentate, I'm sure they'd love to play, pause, stop etc. from the dock so they can have a scene dedicated to videos and manipulate them from a scene decorated to play them so they don't need to jump to them. 

**Describe the solution you'd like**
Open a window similar to they advanced audio properties window, similar to how I show in #25 for the hotkeys per source, that has media controls.

**Comment by FiniteSingularity** [comment]
This functionality is already in the Media Controls plugin (https://github.com/exeldro/obs-media-controls).  If there is a compelling reason to add media control options to this plugin, feel free to re-open.
