### ISSUE TITLE
[FEATURE] - Ability to search browser sources

### ISSUE THREAD

**Issue by mrboost** [FiniteSingularity/obs-quick-access-utility#31]
**Is your feature request related to a problem? Please describe.**
With having multi widgets nested or not. Locating a specific widget by url is next to impossible.

**Describe the solution you'd like**
Ability in the search dock to just simply enter the url for the browser source and quickly find the source(s) that is using that URL

**Comment by FiniteSingularity** [comment]
@mrboost - I haven't forgotten about this.  Currently working on a complete re-write of the search system that adds this, and a bunch of new features.  Stay tuned!

**Comment by mrboost** [comment]
Take your time! Loving the plug-in!

**Comment by FiniteSingularity** [comment]
This was added in the latest pre-release.  (https://github.com/FiniteSingularity/obs-quick-access-utility/releases/tag/0.0.2-alpha7)
