### ISSUE TITLE
[FEATURE] - In the "Add Sources to Manual Dock" window, double click an "Available Source" to add it to "Sources To Add" list

### ISSUE THREAD

**Issue by BoomSoMuch** [FiniteSingularity/obs-quick-access-utility#39]
**Is your feature request related to a problem? Please describe.**
I'm creating Manual Docks with many scenes. Clicking back and forth between scene names and the right arrow button in the Add Sources to Manual Dock window feels slow.

**Describe the solution you'd like**
I double click a source on the left and it pops over to the right.
![image](https://github.com/FiniteSingularity/obs-quick-access-utility/assets/46388061/e746f192-44de-4afc-b1e5-cf96c59e054a)

**Describe alternatives you've considered**
The ability to select multiple sources in the left menu (via ctrl/shift) might be a better solution.

**Comment by FiniteSingularity** [comment]
Just added.
