### ISSUE TITLE
[BUG] - Manual Dock: Scene Selectability Issue

### ISSUE THREAD

**Issue by BoomSoMuch** [FiniteSingularity/obs-quick-access-utility#43]
**Describe the bug**
Hard to put in words but I have a video. If you choose a scene in a manual dock, then switch to another scene elsewhere, you can't click on that scene in the manual dock to return to it. The dock acts as if its already selected.

**To Reproduce**
1. Create two manual docks, each with a few scenes.
2. Select scene 1 in dock 1.
3. Select scene 2 in dock 2.
4. Attempt to select scene 1 again in dock 1. It won't work.

**Screenshots**

https://github.com/FiniteSingularity/obs-quick-access-utility/assets/46388061/ecddd4f3-881a-46cf-9b47-d4534a2a3107

**Environment**
 - OS/Version: Windows 10
 - OBS Version: 30.1.2
 - QAU: Alpha 3
 - Dock Type: Manual

**Comment by FiniteSingularity** [comment]
Just to clarify- when you say "click to go to it" you mean using the Clickable Scenes options?

**Comment by BoomSoMuch** [comment]
> Just to clarify- when you say "click to go to it" you mean using the Clickable Scenes options?

It looks like this issue is closed and fixed, but just to answer the question, you are correct. These were "clickable scenes", but when I clicked it wouldn't switch to the scene under the circumstances described above.
