### ISSUE TITLE
[BUG] - OBS Crashed when closing (not sure if QAU caused it)

### ISSUE THREAD

**Issue by digitaldrummerj** [FiniteSingularity/obs-quick-access-utility#49]
**Describe the bug**

2 crashes:

1. I closed OBS and OBS crashed.  
1. I changed scene collections and OBS crashed.  

Not sure if QAU caused these crash or not but thought I would report it so you can check if QAU was the cause.

**To Reproduce**

** for exiting**
1. Added several manual docks
2. Added 1 search dock
3. Left it open for a bit and when I closed OBS, it crashed

**for changing scene collection**
1. Make you sure you at least 2 scene collection
1. Switch from 1 collection to another collection and OBS crashed

**Expected behavior**

OBS to close and change scene collections normally

**Screenshots**

Here is the crash log for when exiting OBS

[Crash 2024-07-10 09-46-19.txt](https://github.com/user-attachments/files/16165458/Crash.2024-07-10.09-46-19.txt)

Here is a crash log for when changing scene collections in OBS

[Crash 2024-07-10 10-29-11.txt](https://github.com/user-attachments/files/16166933/Crash.2024-07-10.10-29-11.txt)

**Environment**
 - OS/Version: [e.g. Windows 11] Wndows 11
 - OBS Version: [e.g. 29.1.2] 30.1.2
 - Quick Access Utility Version: [e.g. 0.0.1-alpha] 0.0.1-alpha4
 - Dock Type [e.g. Dynamic or Manual] Manual and Search

**GPU**
 - GPU make/model [e.g.- nvidia RTX 3800] RTX 2060
 - GPU VRAM [e.g.- 10Gb] unsure

**Additional context**

**Comment by FiniteSingularity** [comment]
Can you please grab the latest release (https://github.com/FiniteSingularity/obs-quick-access-utility/releases/tag/0.0.1-alpha5) and see if it fixes the crash issue.

**Comment by FiniteSingularity** [comment]
I've been unable to get OBS to crash again on close since this update. I am going to close this as fixed, but @digitaldrummerj, if you continue to have issues, please feel free to re-open.  Fixed by #52
