### ISSUE TITLE
Crashes when arranging scenes [BUG] - Scene arrangement

### ISSUE THREAD

**Issue by cinenotstreamerz** [FiniteSingularity/obs-quick-access-utility#58]
**Describe the bug**
I filtered a new dock of scenes that had "[S]" at the start of each name of the scene. THe only issue was, they were not in the order I wanted, so I clicked on the three bars, to arrange it. It then crashed OBS. 

**Expected behavior**
A clear and concise description of what you expected to happen. I thought I would be able to arrange the scenes.

**Screenshots**

**Environment**
 - OS/Version: [e.g. Windows 11] Windows 11 Pro 64
 - OBS Version:  30.2
 - Quick Access Utility Plugin Version: [e.g. 0.0.1-alpha]
 - Dock Type [e.g. Dynamic or Manual] Source

**GPU**
 - GPU make/model [e.g.- nvidia RTX 3800] Nvidia - GPU 3080 
 - GPU VRAM [e.g.- 10Gb] 10gb

**Additional context**

CRASH LOG

Unhandled exception: c0000005
Date/Time: 2024-07-16, 20:14:29
Fault address: 7FFDD5E140D4 (c:\program files\obs-studio\bin\64bit\qt6core.dll)
libobs version: 30.2.0 (64-bit)
Windows version: 10.0 build 22631 (release: 23H2; revision: 3880; 64-bit)
CPU: 13th Gen Intel(R) Core(TM) i9-13900K

**Comment by FiniteSingularity** [comment]
I am not able to replicate this one right now.  If it happens again, you should get an option to "copy the crash log."  If you can then paste it here, that would be great (what you pasted isn't the whole crash log, and doesnt give me much to go on)

**Comment by FiniteSingularity** [comment]
Closing, as I am not able to replicate this.  If you continue to have the issue @cinenotstreamerz, feel free to reopen.
