### ISSUE TITLE
[BUG] - Crash when using Websocket to create/delete sources.

### ISSUE THREAD

**Issue by reallyjesse** [FiniteSingularity/obs-quick-access-utility#60]
**Describe the bug**
Fatal Crash of OBS when creating sources via a websocket. It appears to work consistently with Streamer.bot while using OBS raw sub-action.

**To Reproduce**
1. Within Streamer.bot or SAMMI that can create multiple sources via OBS Raw, I created an action that will create a source, modify its settings, and then delete the source when complete. (attached screenshots of an example action)
Action Steps:
1. OBS Raw: Create Browser Source
2. OBS Raw: Adjust Browser Position
3. OBS Raw: Create Image Source (GIF).
4. OBS Raw: Adjust GIF Position
5. Set Browser Source URL
6. Toggle Visibility for both sources
7. Delay for length of alert
8. OBS Raw to delete both browser and image source.

Note this doesn't happen every time, but will eventually happen. I can get it to crash if action is done in quick succession with a few second delay between alerts. Additionally, I am noticing a bit of lag from OBS when these items are being created/deleted that doesn't appear when QAU is not installed. 

OBS Logs: https://obsproject.com/logs/J5qlusQxPzBHsBdP

**Screenshots**
Examples of the OBS Raw
![image](https://github.com/user-attachments/assets/455c4bbd-ac09-4c0e-9a09-d184fd8887ba)
![image](https://github.com/user-attachments/assets/f3b2e1a0-f647-4842-bb5e-3965c72ec66f)
![image](https://github.com/user-attachments/assets/49dc89f8-30be-4cbe-9e8a-ca4dbe6c50f2)

**Environment**
 - OS/Version: Windows 11 23H2
 - OBS Version: 30.0
 - Quick Access Utility Plugin Version: [e.g. 0.0.1-alpha]
 - Dock Type (Search, Dynamic, and Manual docks were visible)

**GPU**
 - GPU nvidia RTX 3080ti
 - GPU VRAM

**Additional Information**
Uninstalled QAU and the problem is no longer happening.

**Comment by FiniteSingularity** [comment]
Thank you for the bug report. Which of the releases are you using? The last couple of releases had some fixes for crashes when the source list changes.  If you dont have the latest, please grab it (pre-release alpha6) and see if it resolves things.

**Comment by reallyjesse** [comment]
Alpha6 was the version I was using

**Comment by FiniteSingularity** [comment]
Sounds good.  I'm completely re-doing how scenes/sources are grabbed/released, so hopefully this will be fixed in the next pre-release.  I'll set up a test for this, to make sure its not some strange interaction with how websockets create/destroy sources.

**Comment by FiniteSingularity** [comment]
@reallyjesse This should be fixed in the latest release (alpha 7) or greater.  I set up a Streamerbot streamerbot to add 9 different sources, wait half a second, then delete them all.  Ran the action 50 times, and no crash.  Also had no leaks or issues on shutdown of OBS.  Closing as fixed, but if you're still seeing the problem after installing the latest, please feel free to re-open with more details.
