### ISSUE TITLE
[BUG] - When adding sources, clearing search doesn't show all sources again

### ISSUE THREAD

**Issue by digitaldrummerj** [FiniteSingularity/obs-quick-access-utility#61]
**Describe the bug**

When you are adding sources to a dock, it initially shows all of the sources.  Then if you search for a source and clear out the search box, it does not show all of the sources again

**To Reproduce**
1. Add a new dock
2. Click the + button to add sources
3. Search for a source and if should filter to the search text
4. Clear out the search and the source list will be blank

**Expected behavior**

**Screenshots**

When clearing out the search it should show all of the sources like it does when you click on the + button

**Environment**
 - OS/Version: [e.g. Windows 11] Windows 11
 - OBS Version: [e.g. 29.1.2] 30.1.2
 - Quick Access Utility Plugin Version: [e.g. 0.0.1-alpha] alpha 6
 - Dock Type [e.g. Dynamic or Manual] Manual

**GPU**
 - GPU make/model [e.g.- nvidia RTX 3800] RTX2060
 - GPU VRAM [e.g.- 10Gb] 8 GB

**Additional context**

**Comment by FiniteSingularity** [comment]
I'm currently doing a full rewrite of the search system. This should be fixed when that is ready to go.

**Comment by FiniteSingularity** [comment]
@digitaldrummerj I think this should be fixed in the latest pre-release (https://github.com/FiniteSingularity/obs-quick-access-utility/releases/tag/0.0.2-alpha7). If you can, please give it a try and let me know if it is working properly now.
