### ISSUE TITLE
[Feature] - Activation of Fullscreen Projector (Scene) for a scene from a QAU dock.

### ISSUE THREAD

**Issue by PAvdBerg** [FiniteSingularity/obs-quick-access-utility#63]
Normally you can select Full screen Projector (scene), for example, from the Scenes dock with the right mouse button.

This is not possible in a QAU dock.

The request is to be able to select, for example, Fullscreen Projector (scene) from a QAU dock with the right mouse button.

**Comment by FiniteSingularity** [comment]
I am already working on a windowed projector option, and it will be a part of the 1.0 release.

Full screen projectors are a bit more involved, as the code needs to determine what monitors the user has.  I'd love to get full screen projectors working, but it might not be until after 1.0.

**Comment by FiniteSingularity** [comment]
Windowed projector has been added to the latest pre-release.  The full screen projector is a little trickier, as we need to fetch all of the available displays, but I'm working on it. (you can try out the windowed projector here: https://github.com/FiniteSingularity/obs-quick-access-utility/releases/tag/0.0.2-alpha7 )

**Comment by PAvdBerg** [comment]
Thx.
