### ISSUE TITLE
[BUG] - Plugin is stopping OBS from starting in normal mode.

### ISSUE THREAD

**Issue by rodduarte666** [FiniteSingularity/obs-quick-access-utility#64]
**Describe the bug**
Plugin is stopping OBS from starting in normal mode.

**To Reproduce**
1. Try to open OBS
2. Get error

**Expected behavior**
Obs should start

**Screenshots**
N/A

**Environment**
 - Windows 11
 - OBS Version: 30.2.2
 - Quick Access Utility Plugin Version: 0.0.1-alpha6
 - Dock Type: Both

**GPU**
 - GPU make/model Nvidia RTX 4090
 - GPU VRAM 24gb

**Additional context**
Log attached!
[Crash 2024-08-01 14-29-24.txt](https://github.com/user-attachments/files/16457278/Crash.2024-08-01.14-29-24.txt)

**Comment by FiniteSingularity** [comment]
Hi @rodduarte666,

Sorry to see you're having issues with the plugin.  Looking at the crash log, it looks like something is going wrong when QAU is attempting to load one of your sources. 

If you've got a minute, could you please open OBS in safe mode, then export the scene collection that you're using, and post it here?  I dont need any of the media files or anything, just the scene collection json file.  That'll let me troubleshoot the issue better.

To get you back up and running ASAP, you can either uninstall the QAU plugin until I get a fix pushed out, or if you're comfortable with working in a json file, you can remove the QAU section. If you'd like to do the later, let me know and I can walk you through the process.

**Comment by FiniteSingularity** [comment]
(Also, if you post the scene collection file, I can edit out the QAU stuff, and post a "safe" version of it for you, if you want to keep trying the plugin while I work to fix this issue)

**Comment by rodduarte666** [comment]
OMG yes, I removed it and I miss it dearly, that'd be AWESOME.
Here you go.
[Rods_KICKASS.json](https://github.com/user-attachments/files/16461124/Rods_KICKASS.json)

**Comment by rodduarte666** [comment]
Any update on this? :-)

**Comment by FiniteSingularity** [comment]
From Discord, it sounds like the latest update fixed this issue.  Closing.
