### ISSUE TITLE
[Bug] OBS Crash when removing a source if clickable scenes is turned on.

### ISSUE THREAD

**Issue by REALtony4twenty** [FiniteSingularity/obs-quick-access-utility#9]
I added an image source I had in a scene to the dock. I then tried to remove it and I got this crash. Also, when reopening after crash, the dock is still there but is moved to a new location. Might just be the crashes fault though. I did this 3 times and it happened everytime.

[Crash 2024-06-29 18-41-39.txt](https://github.com/user-attachments/files/16042771/Crash.2024-06-29.18-41-39.txt)

**Comment by FiniteSingularity** [comment]
Just to confirm- this is in a manual dock?  I just realized I tested the heck out of sources being added/removed from the dynamic docs, but didnt test the manual dock too much.

**Comment by REALtony4twenty** [comment]
So far it only happened with an image source, I removed the scene the image was in just now and it did not crash. Also the dock moving was, Im assuming, related to it just simply not saving correctly since I crashed it again using the image source and it is no longer moving the dock. Yes it is a manual dock..

**Comment by REALtony4twenty** [comment]
So after deleting the scene and it being fine, I purposely crashed it with the image again as stated above. 
Well upon re-opening I noticed the scene was back again, I figured it was probably just a bad save again from the crash. 
So I deleted the scene from the dock, closed OBS, reopened it and now the dock is gone and the utility is no longer in the tools tab

**Comment by REALtony4twenty** [comment]
closed and reopened, and now its back with the scene deleted. Strange

> So after deleting the scene and it being fine, I purposely crashed it with the image again as stated above. Well upon re-opening I noticed the scene was back again, I figured it was probably just a bad save again from the crash. So I deleted the scene from the dock, closed OBS, reopened it and now the dock is gone and the utility is no longer in the tools tab

**Comment by FiniteSingularity** [comment]
When it crashes, it isn't updating the save file.  I'm guessing that when you tried to re-open, and there was a source in your dock that didn't exist, it threw a fit.  I'll need to add some error checking when loading in the docks, as well as the fix so that it removes the source from your dock when it is deleted from OBS.

**Comment by FiniteSingularity** [comment]
Ok, this has been narrowed down to occurring if you remove a source from a manual list, when clickable scenes is on.
